[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["daiju81 <1d07c.m8k.prv@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"